apt:
  sources:
  - deb http://archive.ubuntu.com/ubuntu/ bionic main restricted
  - deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted
  - deb http://archive.ubuntu.com/ubuntu/ bionic universe
  - deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe
  - deb http://archive.ubuntu.com/ubuntu/ bionic multiverse
  - deb http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse
  - deb http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe
    multiverse
  - deb http://security.ubuntu.com/ubuntu bionic-security main restricted
  - deb http://security.ubuntu.com/ubuntu bionic-security universe
  - deb http://security.ubuntu.com/ubuntu bionic-security multiverse
  packages:
  - libselinux1:amd64=2.7-2build2
  - libuuid1:amd64=2.31.1-0.4ubuntu3.7
  - libcups2:amd64=2.2.7-1ubuntu2.9
  - glib-networking-common:all=2.56.0-1ubuntu0.1
  - libxinerama1:amd64=2:1.1.3-1
  - libidn2-0:amd64=2.0.4-1.1ubuntu0.2
  - libcom-err2:amd64=1.44.1-1ubuntu1.4
  - liblcms2-2:amd64=2.9-1ubuntu0.1
  - libexpat1:amd64=2.2.5-3ubuntu0.9
  - libgmp10:amd64=2:6.1.2+dfsg-2ubuntu0.1
  - libxext6:amd64=2:1.3.3-1
  - libicu60:amd64=60.2-3ubuntu3.2
  - libfontconfig1:amd64=2.12.6-0ubuntu2
  - glib-networking:amd64=2.56.0-1ubuntu0.1
  - libudev1:amd64=237-3ubuntu10.56
  - libatk1.0-0:amd64=2.28.1-1
  - librest-0.7-0:amd64=0.8.0-2
  - libjbig0:amd64=2.1-3.1ubuntu0.18.04.1
  - libp11-kit0:amd64=0.23.9-2ubuntu0.1
  - libgpg-error0:amd64=1.27-6
  - libgraphite2-3:amd64=1.3.11-2
  - libgdk-pixbuf2.0-common:all=2.36.11-2
  - libxml2:amd64=2.9.4+dfsg1-6.1ubuntu1.8
  - libkrb5support0:amd64=1.16-2ubuntu0.2
  - libavahi-common-data:amd64=0.7-3.1ubuntu1.3
  - libhogweed4:amd64=3.4.1-0ubuntu0.18.04.1
  - xkb-data:all=2.23.1-1ubuntu1.18.04.1
  - libnettle6:amd64=3.4.1-0ubuntu0.18.04.1
  - gsettings-desktop-schemas:all=3.28.0-1ubuntu1
  - libcairo2:amd64=1.15.10-2ubuntu0.1
  - libdatrie1:amd64=0.2.10-7
  - libthai0:amd64=0.1.27-2
  - libatk-bridge2.0-0:amd64=2.26.2-1
  - libxkbcommon0:amd64=0.8.2-1~ubuntu18.04.1
  - libpangoft2-1.0-0:amd64=1.40.14-1ubuntu0.1
  - libglib2.0-0:amd64=2.56.4-0ubuntu0.18.04.9
  - libgssapi-krb5-2:amd64=1.16-2ubuntu0.2
  - libsoup2.4-1:amd64=2.62.1-1ubuntu0.4
  - libffi6:amd64=3.2.1-8
  - libxcursor1:amd64=1:1.1.15-1
  - libk5crypto3:amd64=1.16-2ubuntu0.2
  - libfreetype6:amd64=2.8.1-2ubuntu2.2
  - libwayland-egl1:amd64=1.16.0-1ubuntu1.1~18.04.4
  - libpango-1.0-0:amd64=1.40.14-1ubuntu0.1
  - liblzma5:amd64=5.2.2-1.3ubuntu0.1
  - libcairo-gobject2:amd64=1.15.10-2ubuntu0.1
  - libtiff5:amd64=4.0.9-5ubuntu0.9
  - gcc-8-base:amd64=8.4.0-1ubuntu1~18.04
  - libatk1.0-data:all=2.28.1-1
  - libjson-glib-1.0-common:all=1.4.2-3ubuntu0.18.04.1
  - libmount1:amd64=2.31.1-0.4ubuntu3.7
  - libdbus-1-3:amd64=1.12.2-1ubuntu1.4
  - libwayland-client0:amd64=1.16.0-1ubuntu1.1~18.04.4
  - libxfixes3:amd64=1:5.0.3-1
  - libjpeg8:amd64=8c-2ubuntu8
  - libxcomposite1:amd64=1:0.4.4-2
  - zlib1g:amd64=1:1.2.11.dfsg-0ubuntu2.2
  - libsqlite3-0:amd64=3.22.0-1ubuntu0.7
  - libkeyutils1:amd64=1.5.9-9.2ubuntu2.1
  - libharfbuzz0b:amd64=1.7.2-1ubuntu1
  - dconf-service:amd64=0.26.0-2ubuntu3
  - libxrender1:amd64=1:0.9.10-1
  - libc6:amd64=2.27-3ubuntu1.6
  - libpng16-16:amd64=1.6.34-1ubuntu0.18.04.2
  - glib-networking-services:amd64=2.56.0-1ubuntu0.1
  - libpangocairo-1.0-0:amd64=1.40.14-1ubuntu0.1
  - libgtk-3-common:all=3.22.30-1ubuntu4
  - libxdamage1:amd64=1:1.1.4-3
  - libthai-data:all=0.1.27-2
  - libjson-glib-1.0-0:amd64=1.4.2-3ubuntu0.18.04.1
  - liblz4-1:amd64=0.0~r131-2ubuntu3.1
  - libxi6:amd64=2:1.7.9-1
  - libxrandr2:amd64=2:1.5.1-1
  - libkrb5-3:amd64=1.16-2ubuntu0.2
  - libavahi-common3:amd64=0.7-3.1ubuntu1.3
  - libstdc++6:amd64=8.4.0-1ubuntu1~18.04
  - libdconf1:amd64=0.26.0-2ubuntu3
  - libunistring2:amd64=0.9.9-0ubuntu2
  - libatspi2.0-0:amd64=2.28.0-1
  - libcolord2:amd64=1.3.3-2build1
  - libtasn1-6:amd64=4.13-2
  - libgcrypt20:amd64=1.8.1-4ubuntu1.3
  - libgdk-pixbuf2.0-0:amd64=2.36.11-2
  - dconf-gsettings-backend:amd64=0.26.0-2ubuntu3
  - libpixman-1-0:amd64=0.34.0-2ubuntu0.1
  - libblkid1:amd64=2.31.1-0.4ubuntu3.7
  - libpcre3:amd64=2:8.39-9ubuntu0.1
  - libjpeg-turbo8:amd64=1.5.2-0ubuntu5.18.04.6
  - libsystemd0:amd64=237-3ubuntu10.56
  - libwayland-cursor0:amd64=1.16.0-1ubuntu1.1~18.04.4
  - libavahi-client3:amd64=0.7-3.1ubuntu1.3
  - libproxy1v5:amd64=0.4.15-1ubuntu0.2
  - libgtk-3-0:amd64=3.22.30-1ubuntu4
  - libepoxy0:amd64=1.4.3-1
  - libgnutls30:amd64=3.5.18-1ubuntu1.6
  - libsoup-gnome2.4-1:amd64=2.62.1-1ubuntu0.4
  - libgcc1:amd64=1:8.4.0-1ubuntu1~18.04
